### PR TITLE
Fix conversion of shell script step

### PR DESCRIPTION
**Pull request by arichardson**
Currently the sh step uses `"""` so groovy attempt to expand any `${FOO}` variables but they should actually be parsed by the shell instead. To fix this I changed it to use a `'''` string.
Also inserting a newline before the script contents will break any `#!` interpreter selection. I fixed this by only adding a newline if the script doesn't start with `#!`

### CODE REVIEW

**Comment by arichardson** [comment]
We have a lot of jobs with custom shell scripts that need `#!/bin/bash` and use shell variables.

Could you please review this change?

**Comment by ghost** [comment]
Thank you for this PR.
I agree with the fix that you are proposing; however this will solve 1 bug in the plugin.
We are currently evaluating this fork that was suggested in a different conversation: https://github.com/daniel-beck/convert-to-pipeline/tree/generic-fallback-support
There is more work required on this fork which will not only solve the bug you have pointed out but also handle support for several other plugins that become compatible with the pipeline suit and possibly iron out any other bugs that may have been missed.

**Comment by arichardson** [comment]
That does seem very promising. In this pull request I also made some refactoring to be able to add unit tests. Would it make sense to extract those changes and rebase them on top of https://github.com/daniel-beck/convert-to-pipeline/tree/generic-fallback-support ?

**Review by tusharajmeriya — APPROVED** [review]

**Review by vimal-infostretch — APPROVED** [review]
Approved.

**Review by vimal-infostretch — COMMENTED** [review]
if we change POM.xml with `<skipTests>false</skipTests>.` It gives errors. Is there any other changes needs to be done either in POM.xml or somewhere else?

Error : [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)

**Pull request merged**
